### ISSUE TITLE
[RFE] Specify update.conf directives as annotations

### ISSUE THREAD

**Issue by tijmenvandenbrink** [flatcar/flatcar-linux-update-operator#204] opened 2024-06-06 10:58 UTC
## Current situation

Currently we specify the `SERVER`, `GROUP` and `MACHINE_ALIAS` in `/etc/flatcar/update.conf` when bootstrapping a node. This makes it quite static as we're not touching/actively managing this file after initial bootstrap.

## Impact

At this point there is no way to manage these directives via Kubernetes which forces us to manually change it on the host.

## Ideal future situation

Ideally we would be able to set annotations on a node specifying `SERVER`, `GROUP` and `MACHINE_ALIAS` which overrides the directives in `/etc/flatcar/update.conf`. This would give us a lot of flexibility in controlling which versions run within a cluster. A specific use case I see is running a small set of beta release nodes in a cluster allowing for early detection of issues.

## Implementation options

[ Optional: please provide one or more options for implementing the feature requested ]

## Additional information

[ Please Add any information that does not fit into any of the above sections here ]

**Comment by invidian** [comment] 2024-06-17 15:30
Thank you for reporting. I'll close this as duplicate of https://github.com/flatcar/flatcar-linux-update-operator/issues/34 since IIUC is about the same thing.

**Closed by invidian** 2024-06-17 15:30 UTC
